#Madlibs Game
adj1 = input("Enter an adjective: ")
verb = input("Enter a verb ending with 'ing' : ")
adj2 = input("Enter another adjective: ")
noun1 = input("Enter a noun: ")
adj3 = input("Enter the last adjective: ")
noun2 = input("Enter another noun: ")
print(". . . . . . . . . . . .")
print("Here is the madlibs: ")
print("----------------------------------")
print(f"I watched {adj1} movie")
print(f"While {verb} and watching the movie I felt {adj2}!!")
print(f"{noun1} in the movie was so {adj3}!")
print(f"I love {noun2}")